### ISSUE TITLE
make "team" images smaller

### ISSUE THREAD

**Issue by mpadge** [moveability/moweb#10]
They're currently unnecessarily large, and would look much better about half that size or so

**Comment by silberzwiebel** [comment]
I'm gonna take care of this.

**Comment by silberzwiebel** [comment]
Too small? Still too big? Here is the config: https://github.com/moveability/moweb/blob/ac81d2914b53b0079ba4edde1c05a94d0cbbefe2/themes/hugo-agency-theme/static/css/agency.css#L681
