### ISSUE TITLE
default click through to maps

### ISSUE THREAD

**Issue by mpadge** [moveability/moweb#11]
There are currently at least 2 places where this would be good as default behaviour

1. "Move me" on the front page. Easily done in `config.toml`
2. The currently inactive "Get your city moving" non-button at the bottom of "About". That will require modifying the theme itself.

**Comment by silberzwiebel** [comment]
Assigning this to myself, too. Not sure about the second place, though. Shouldn't this rather link to the contact form (that I'm going to fix first)?
